name: Security Scan  # Nome do seu pipeline

on: [push]  # Roda automaticamente quando você faz git push

jobs:
  sast:  # Análise estática (SAST) com Syhunt
    runs-on: ubuntu-latest  # Roda em um servidor Linux
    steps:
      - uses: actions/checkout@v3  # Baixa seu código
      - name: Run Syhunt SAST
        uses: syhunt/github-action@main  # Usa a ação do Syhunt
        with:
          api-key: ${{ secrets.SYHUNT_API_KEY }}  # Chave de API (vamos configurar)
          target: ./  # Escaneia todo o repositório

  dast:  # Análise dinâmica (DAST) com OWASP ZAP
    runs-on: ubuntu-latest
    needs: [sast]  # Só roda depois do SAST
    steps:
      - uses: actions/checkout@v3
      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0  # Ação do ZAP
        with:
          target: 'http://localhost:3000'  # Altere para sua URL
          # Se sua página não estiver online, use uma ação para subir um servidor local
