name: Security Scan
on: [push]

jobs:
  sast:
    runs-on: ubuntu-latest  # Note: Isso roda na nuvem do GitHub, não no seu runner local!
    steps:
      - uses: actions/checkout@v3
      - name: Run Syhunt SAST
        run: |
          # Aqui você precisaria ter o Syhunt instalado no ambiente Ubuntu
          # Como não é seu caso, vamos modificar para usar seu runner local
          
  # VAMOS MODIFICAR PARA USAR SEU RUNNER AUTO-HOSPEDADO
  syhunt-sast:
    runs-on: self-hosted  # Isso fará usar SEU runner local
    steps:
      - uses: actions/checkout@v3
      - name: Run Syhunt from Pendrive
        run: |
          "D:\syhunt-community-7.0.10.3.exe" scan --target . --api-key=${{ secrets.SYHUNT_API_KEY }}
        shell: cmd  # Usa o shell do Windows

  dast:
    runs-on: ubuntu-latest
    needs: [syhunt-sast]
    steps:
      - uses: actions/checkout@v3
      
      - name: Start Local Server
        run: |
          # Instala o http-server localmente (sem -g) e roda
          npm install http-server
          npx http-server ./ -p 3000 &
          
      - name: Wait for server to start
        run: sleep 5  # Dá tempo para o servidor iniciar
        
      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:3000'
