name: Security Scan
on: [push]

jobs:
  sast:
    runs-on: ubuntu-latest  # Note: Isso roda na nuvem do GitHub, não no seu runner local!
    steps:
      - uses: actions/checkout@v3
      - name: Run Syhunt SAST
        run: |
          # Aqui você precisaria ter o Syhunt instalado no ambiente Ubuntu
          # Como não é seu caso, vamos modificar para usar seu runner local
          
  # VAMOS MODIFICAR PARA USAR SEU RUNNER AUTO-HOSPEDADO
  syhunt-sast:
    runs-on: self-hosted  # Isso fará usar SEU runner local
    steps:
      - uses: actions/checkout@v3
      - name: Run Syhunt from Pendrive
        run: |
          "D:\syhunt-community-7.0.10.3.exe" scan --target . --api-key=${{ secrets.SYHUNT_API_KEY }}
        shell: cmd  # Usa o shell do Windows

  dast:
    runs-on: ubuntu-latest
    needs: [syhunt-sast]
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install and start server
        run: |
          yarn add http-server --dev
          yarn run http-server ./ -p 3000 &
          sleep 10  # Tempo extra para garantir que o servidor iniciou
          
      - name: Prepare ZAP
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          
      - name: Run ZAP Scan (with retry)
        id: zap-scan
        continue-on-error: true  # Continua mesmo com falhas para capturar logs
        run: |
          docker run --rm \
            -v $(pwd):/zap/wrk:rw \
            -e ZAP_AUTH_HEADER \
            -e ZAP_AUTH_HEADER_VALUE \
            -e ZAP_AUTH_HEADER_SITE \
            owasp/zap2docker-stable \
            zap-baseline.py \
            -t http://host.docker.internal:3000 \
            -J report.json \
            -w report.md \
            -r report.html \
            -c zap.conf || echo "ZAP scan completed with exit code $?"
            
      - name: Upload results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-results
          path: |
            report.json
            report.md
            report.html
            zap.log
