name: Security Scan
on: [push]

jobs:
  sast:
    runs-on: ubuntu-latest  # Note: Isso roda na nuvem do GitHub, não no seu runner local!
    steps:
      - uses: actions/checkout@v3
      - name: Run Syhunt SAST
        run: |
          # Aqui você precisaria ter o Syhunt instalado no ambiente Ubuntu
          # Como não é seu caso, vamos modificar para usar seu runner local
          
  # VAMOS MODIFICAR PARA USAR SEU RUNNER AUTO-HOSPEDADO
  syhunt-sast:
    runs-on: self-hosted  # Isso fará usar SEU runner local
    steps:
      - uses: actions/checkout@v3
      - name: Run Syhunt from Pendrive
        run: |
          "D:\syhunt-community-7.0.10.3.exe" scan --target . --api-key=${{ secrets.SYHUNT_API_KEY }}
        shell: cmd  # Usa o shell do Windows

  dast:
  
    runs-on: ubuntu-latest
    needs: [syhunt-sast]
    permissions:
      actions: write
      checks: write
      security-events: write
      contents: read
  
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install http-server
        run: yarn add http-server --dev
      
      - name: Start Local Server
        run: |
          yarn run http-server ./ -p 3000 &
          sleep 5
          
      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:3000'
          cmd_options: '-J report_json.json -w report_md.md -r report_html.html'
        continue-on-error: true  # Continua mesmo se encontrar vulnerabilidades
        
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: zap-report
          path: |
            report_json.json
            report_md.md
            report_html.html
  
