name: Security Scan
on: [push]

jobs:
  sast:
    runs-on: ubuntu-latest  # Note: Isso roda na nuvem do GitHub, não no seu runner local!
    steps:
      - uses: actions/checkout@v3
      - name: Run Syhunt SAST
        run: |
          # Aqui você precisaria ter o Syhunt instalado no ambiente Ubuntu
          # Como não é seu caso, vamos modificar para usar seu runner local
          
  # VAMOS MODIFICAR PARA USAR SEU RUNNER AUTO-HOSPEDADO
  syhunt-sast:
    runs-on: self-hosted  # Isso fará usar SEU runner local
    steps:
      - uses: actions/checkout@v3
      - name: Run Syhunt from Pendrive
        run: |
          "D:\syhunt-community-7.0.10.3.exe" scan --target . --api-key=${{ secrets.SYHUNT_API_KEY }}
        shell: cmd  # Usa o shell do Windows

  dast:
    runs-on: self-hosted  # Usa seu runner local
    needs: [sast]
    steps:
      - uses: actions/checkout@v4
      
      - name: Start test server
        run: |
          yarn add http-server --dev
          yarn run http-server ./ -p 3000 &
          sleep 5
          
      - name: Run Syhunt Dynamic Scan
        run: |
          "D:\syhunt-dynamic\syhunt-dynamic.exe" scan --target http://localhost:3000 --api-key=${{ secrets.SYHUNT_API_KEY }}
        shell: cmd
        
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: dast-report
          path: report.html  # O Syhunt gera automaticamente
